steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/witnessme', '-f', 'dockerfiles/Dockerfile.gcloud', '.']
  timeout: 500s
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/witnessme']

timeout: 660s
images:
- gcr.io/$PROJECT_ID/witnessmes